---
influx:
  host: 127.0.0.1
  port: 8086
  user: test
  pass: test
  db: test
tuya:  # follow https://pypi.org/project/tinytuya/
  - measurement: room001
    ip: 192.168.0.2
    id: aaaaaaaaaaaaaaaaaaaa
    key: aaaaaaaaaaaaaaaa
  - measurement: room002
    ip: 192.168.0.3
    id: bbbbbbbbbbbbbbbbbbbb
    key: bbbbbbbbbbbbbbbb
