---
influx:
  host: 127.0.0.1
  port: 8086
  user: test
  pass: test
  db: test
  measurement: SmartAirBox_Study
tuya:  # follow https://pypi.org/project/tinytuya/
  ip: 192.168.0.2
  id: aaaaaaaaaaaaaaaaaaaa
  key: aaaaaaaaaaaaaaaa
